-- Fixed lock buckets contain no provider or user identifiers.
CREATE TABLE oauth_lifecycle_locks (bucket_id INT PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO oauth_lifecycle_locks(bucket_id)
SELECT ones.n + tens.n * 8 FROM
(SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) ones
CROSS JOIN
(SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7) tens;
